// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alerts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns paginated alerts owned by the authenticated client. Filter by ` + "`" + `device_id` + "`" + `, one or more ` + "`" + `severity` + "`" + ` values (` + "`" + `info` + "`" + `, ` + "`" + `warning` + "`" + `, ` + "`" + `critical` + "`" + `), a time range on ` + "`" + `occurred_at` + "`" + `, and ` + "`" + `search` + "`" + ` over alert message, alert type, device name, or exact device UUID. Results are scoped to the current client and ordered by ` + "`" + `occurred_at DESC, id DESC` + "`" + `. The response never includes ` + "`" + `client_id` + "`" + ` or any device API key material.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alerts"
                ],
                "summary": "List alerts for the authenticated client",
                "parameters": [
                    {
                        "type": "string",
                        "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234",
                        "description": "Filter to a single device id (UUID)",
                        "name": "device_id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "info",
                                "warning",
                                "critical"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by severity. Repeat to combine, e.g. severity=warning\u0026severity=critical",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2026-05-01T00:00:00Z",
                        "description": "Inclusive lower bound on occurred_at, RFC3339",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2026-05-04T23:59:59Z",
                        "description": "Inclusive upper bound on occurred_at, RFC3339",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "maxLength": 100,
                        "minLength": 2,
                        "type": "string",
                        "example": "smoke",
                        "description": "Search alert message, alert type, device name, or exact device UUID",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number, starts at 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alerts retrieved successfully with pagination metadata.",
                        "schema": {
                            "$ref": "#/definitions/alert.ListAlertsResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error on filters or pagination.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/alerts/stream": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Opens an SSE connection for the authenticated client. Use client JWT auth (` + "`" + `Authorization: Bearer \u003caccess_token\u003e` + "`" + `), not a device API key. The stream immediately sends ` + "`" + `event: connected` + "`" + `, then sends ` + "`" + `event: alert` + "`" + ` whenever one of the client's devices ingests an alert, and sends ` + "`" + `event: heartbeat` + "`" + ` every 30 seconds to keep the connection alive. Optional ` + "`" + `device_id` + "`" + ` filters alerts to one device owned by the client. Events from other clients are never delivered.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Alerts"
                ],
                "summary": "Stream realtime alerts to an authenticated client with Server-Sent Events",
                "parameters": [
                    {
                        "type": "string",
                        "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234",
                        "description": "Optional device UUID filter. When set, only alerts for this device are sent.",
                        "name": "device_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream. Event types: connected, alert, heartbeat.",
                        "schema": {
                            "$ref": "#/definitions/alert.StreamAlertEvent"
                        }
                    },
                    "400": {
                        "description": "Invalid device_id query parameter.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid client access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticates by email and password. The response returns a short-lived JWT access token plus an opaque refresh token. Invalid email and invalid password both return the same unauthorized response so credential existence is not leaked.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login an existing client and issue tokens",
                "parameters": [
                    {
                        "description": "Client login payload. Development demo credentials: client@example.com / password123.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful; use data.access_token in the BearerAuth authorize button.",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes active client-token sessions for the authenticated client. Send only ` + "`" + `Authorization: Bearer \u003caccess_token\u003e` + "`" + `; no request body is required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout the current authenticated client",
                "responses": {
                    "200": {
                        "description": "Logout successful.",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes every active client-token session owned by the authenticated client. Use this when the client wants to sign out from all devices/browsers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout all sessions for the current client",
                "responses": {
                    "200": {
                        "description": "All sessions logged out successfully.",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Exchanges a valid refresh_token for a new access_token and refresh_token. The submitted refresh token is marked used/replaced; reusing an old replaced refresh token revokes its token family and returns 401.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Rotate a refresh token and issue a new access token",
                "parameters": [
                    {
                        "description": "Refresh payload containing the raw refresh_token from register/login/previous refresh.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token refreshed successfully; replace the old refresh_token with the new one.",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error, such as missing refresh_token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid, expired, revoked, or reused refresh token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a client account with name, unique email, and password. The response intentionally returns only access_token, refresh_token, token_type, and expires_in; it does not return client profile data. Use the access token as ` + "`" + `Authorization: Bearer \u003caccess_token\u003e` + "`" + ` for protected APIs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new client and issue tokens",
                "parameters": [
                    {
                        "description": "Client registration payload. Password must be at least 8 characters.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Client registered successfully; refresh_token is shown only in this response and is stored server-side only as a hash in client_tokens.",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error, such as invalid email or short password.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email already exists.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns active and historical client-token sessions for the authenticated client. Raw refresh tokens and token hashes are never returned; only safe session metadata such as id, token_family, timestamps, user_agent, and ip_address are exposed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "List current client's token sessions",
                "responses": {
                    "200": {
                        "description": "Sessions retrieved successfully. Use a session id from this response with DELETE /auth/sessions/{id}.",
                        "schema": {
                            "$ref": "#/definitions/auth.SessionsResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/sessions/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes a single session owned by the authenticated client. The id must come from GET /auth/sessions. Revocation is scoped by client ownership, so a client cannot revoke another client's session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Revoke one client-token session",
                "parameters": [
                    {
                        "type": "string",
                        "example": "9fe9e122-bfb1-4f3b-a2d0-f4acdd4cbd2d",
                        "description": "Session ID from GET /auth/sessions",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session revoked successfully.",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid session id.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing/invalid access token or session does not belong to the client.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile for the client identified by the Bearer access token. This endpoint never returns password hashes, refresh tokens, or client_tokens records.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Client"
                ],
                "summary": "Get the authenticated client profile",
                "responses": {
                    "200": {
                        "description": "Current client profile.",
                        "schema": {
                            "$ref": "#/definitions/client.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Authenticated client no longer exists.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns paginated devices for the current client. By default soft-deleted devices are hidden. Use ` + "`" + `status` + "`" + ` to satisfy Backlog 1 filtering by device status; combine with ` + "`" + `type` + "`" + ` when needed. Allowed status values: active, inactive, maintenance, error. Allowed type values: temperature_sensor, humidity_sensor, smoke_detector, motion_sensor, door_sensor, camera, gateway, other.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "List devices owned by the authenticated client",
                "parameters": [
                    {
                        "enum": [
                            "active",
                            "inactive",
                            "maintenance",
                            "error"
                        ],
                        "type": "string",
                        "description": "Filter by device status: active, inactive, maintenance, error",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "temperature_sensor",
                            "humidity_sensor",
                            "smoke_detector",
                            "motion_sensor",
                            "door_sensor",
                            "camera",
                            "gateway",
                            "other"
                        ],
                        "type": "string",
                        "description": "Filter by device type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Set true to include soft-deleted devices",
                        "name": "include_deleted",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number, starts at 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Devices retrieved successfully with pagination metadata.",
                        "schema": {
                            "$ref": "#/definitions/device.ListDevicesResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid status, type, or pagination input.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates an IoT device owned by the current client. ` + "`" + `type` + "`" + ` must be one of: temperature_sensor, humidity_sensor, smoke_detector, motion_sensor, door_sensor, camera, gateway, other. ` + "`" + `status` + "`" + ` is optional and defaults to active; allowed values are active, inactive, maintenance, error. Device names must be unique per client among non-deleted devices. The generated api_key is returned only once in this response and only its hash is stored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Register a new device for the authenticated client",
                "parameters": [
                    {
                        "description": "Device registration payload. tags and metadata are optional.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/device.CreateDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Device created successfully; save data.api_key because it cannot be retrieved later.",
                        "schema": {
                            "$ref": "#/definitions/device.CreateDeviceEnvelopeResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error, invalid device type, or invalid status.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "A non-deleted device with the same name already exists for this client.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a non-deleted device owned by the authenticated client. Soft-deleted devices are not returned by this endpoint unless they are restored first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Get one device by ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Device retrieved successfully.",
                        "schema": {
                            "$ref": "#/definitions/device.DeviceEnvelopeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid device id.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found for this client or device is soft-deleted.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft deletes a device owned by the authenticated client by setting deleted_at. Deleted devices are hidden from normal list/detail APIs. The response includes purge_after, which is the point after the configured restore window.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Soft delete a device",
                "parameters": [
                    {
                        "type": "string",
                        "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Device deleted successfully; data.deleted_at and data.purge_after describe the deletion lifecycle.",
                        "schema": {
                            "$ref": "#/definitions/device.DeleteDeviceEnvelopeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid device id.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found for this client.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partially updates a non-deleted device owned by the authenticated client. Send only the fields you want to change. Allowed status values: active, inactive, maintenance, error. Allowed type values: temperature_sensor, humidity_sensor, smoke_detector, motion_sensor, door_sensor, camera, gateway, other. Device name uniqueness is enforced per client among non-deleted devices.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Update a device",
                "parameters": [
                    {
                        "type": "string",
                        "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Partial update payload. Omitted fields keep their existing values.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/device.UpdateDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Device updated successfully.",
                        "schema": {
                            "$ref": "#/definitions/device.DeviceEnvelopeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid device id, invalid type/status, validation error, or deleted device cannot be changed.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found for this client.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Updated name conflicts with another active device owned by the client.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{id}/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restores a device deleted within the configured restore window. Restored devices are set to inactive so the client can review them before using them again. Restore can fail if another active device now uses the same name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Restore a soft-deleted device",
                "parameters": [
                    {
                        "type": "string",
                        "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Device restored successfully; restored status is inactive.",
                        "schema": {
                            "$ref": "#/definitions/device.DeviceEnvelopeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid device id, device is not deleted, or restore window expired.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found for this client.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Restore conflicts with another active device name.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{id}/rotate-key": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates a new API key for a non-deleted device owned by the authenticated client and replaces the stored hash. The raw api_key is returned only once in this response; store it immediately because it cannot be retrieved later.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Rotate a device API key",
                "parameters": [
                    {
                        "type": "string",
                        "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Device API key rotated successfully.",
                        "schema": {
                            "$ref": "#/definitions/device.RotateDeviceAPIKeyEnvelopeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid device id or deleted device cannot be changed.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found for this client.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events": {
            "post": {
                "security": [
                    {
                        "DeviceAPIKey": []
                    }
                ],
                "description": "Accepts one append-only alert event from an authenticated device. Authenticate with the raw device API key returned by POST /devices or POST /devices/{id}/rotate-key using ` + "`" + `Authorization: Bearer ah_dev_...` + "`" + `. The API stores only the alert row, emits a PostgreSQL NOTIFY event for SSE subscribers, and never exposes api_key/api_key_hash in the response. ` + "`" + `severity` + "`" + ` must be one of info, warning, critical; ` + "`" + `type` + "`" + ` is a free string up to 100 characters; ` + "`" + `payload` + "`" + ` is optional JSON metadata; ` + "`" + `occurred_at` + "`" + ` is optional and defaults to server time.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alerts"
                ],
                "summary": "Ingest one realtime alert event from a device",
                "parameters": [
                    {
                        "description": "Single alert payload. Example severity values: info, warning, critical.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/alert.IngestRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Event accepted; data.alert_id can be used to correlate stream events.",
                        "schema": {
                            "$ref": "#/definitions/alert.IngestEnvelopeResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error: invalid severity, blank type, blank message, malformed JSON.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing, invalid, or soft-deleted device API key.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal insert or notify error.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/batch": {
            "post": {
                "security": [
                    {
                        "DeviceAPIKey": []
                    }
                ],
                "description": "Accepts up to 100 alert events from one authenticated device. Valid events are inserted and notified; invalid events are returned in data.errors with their original index, so clients can retry only failed items. The response can contain both accepted alerts and rejected errors. Authentication uses ` + "`" + `Authorization: Bearer ah_dev_...` + "`" + ` with the raw device API key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alerts"
                ],
                "summary": "Ingest a batch of realtime alert events from a device",
                "parameters": [
                    {
                        "description": "Batch payload. events must contain 1..100 items. Partial failure is reported per index.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/alert.BatchRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Batch fully accepted; check data.accepted, data.alerts, and data.errors.",
                        "schema": {
                            "$ref": "#/definitions/alert.BatchEnvelopeResponse"
                        }
                    },
                    "207": {
                        "description": "Batch partially accepted; check data.accepted, data.rejected, data.alerts, and data.errors.",
                        "schema": {
                            "$ref": "#/definitions/alert.BatchEnvelopeResponse"
                        }
                    },
                    "400": {
                        "description": "Empty batch, more than 100 events, malformed JSON, or invalid batch shape.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing, invalid, or soft-deleted device API key.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal insert or notify error.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "alert.AlertPaginationMeta": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean",
                    "example": true
                },
                "has_previous": {
                    "type": "boolean",
                    "example": false
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "alert.AlertResponse": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234"
                },
                "id": {
                    "type": "string",
                    "example": "9f3d2e1a-1234-4321-abcd-1234567890ab"
                },
                "message": {
                    "type": "string",
                    "example": "Temperature exceeded 80°C"
                },
                "occurred_at": {
                    "type": "string"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": true
                },
                "received_at": {
                    "type": "string"
                },
                "severity": {
                    "type": "string",
                    "example": "warning"
                },
                "type": {
                    "type": "string",
                    "example": "high_temperature"
                }
            }
        },
        "alert.BatchAcceptedAlert": {
            "type": "object",
            "properties": {
                "alert_id": {
                    "type": "string",
                    "example": "9f3d2e1a-1234-4321-abcd-1234567890ab"
                },
                "index": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "alert.BatchEnvelopeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/alert.BatchResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Batch processed"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "alert.BatchError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_SEVERITY"
                },
                "index": {
                    "type": "integer",
                    "example": 5
                },
                "message": {
                    "type": "string",
                    "example": "severity must be one of info, warning, critical"
                }
            }
        },
        "alert.BatchRequest": {
            "type": "object",
            "required": [
                "events"
            ],
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert.IngestRequest"
                    }
                }
            }
        },
        "alert.BatchResponse": {
            "type": "object",
            "properties": {
                "accepted": {
                    "type": "integer",
                    "example": 98
                },
                "alerts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert.BatchAcceptedAlert"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert.BatchError"
                    }
                },
                "rejected": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "alert.IngestEnvelopeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/alert.IngestResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Event accepted"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "alert.IngestRequest": {
            "type": "object",
            "required": [
                "message",
                "severity",
                "type"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Temperature exceeded 80°C"
                },
                "occurred_at": {
                    "type": "string",
                    "example": "2026-05-03T12:00:00Z"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": true
                },
                "severity": {
                    "type": "string",
                    "example": "warning"
                },
                "type": {
                    "type": "string",
                    "example": "high_temperature"
                }
            }
        },
        "alert.IngestResponse": {
            "type": "object",
            "properties": {
                "alert_id": {
                    "type": "string",
                    "example": "9f3d2e1a-1234-4321-abcd-1234567890ab"
                },
                "received_at": {
                    "type": "string",
                    "example": "2026-05-03T12:00:00.123Z"
                }
            }
        },
        "alert.ListAlertsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert.AlertResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Alerts retrieved successfully"
                },
                "pagination": {
                    "$ref": "#/definitions/alert.AlertPaginationMeta"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "alert.StreamAlertEvent": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234"
                },
                "id": {
                    "type": "string",
                    "example": "9f3d2e1a-1234-4321-abcd-1234567890ab"
                },
                "message": {
                    "type": "string",
                    "example": "Temperature exceeded 80°C"
                },
                "occurred_at": {
                    "type": "string",
                    "example": "2026-05-03T12:00:00Z"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": true
                },
                "received_at": {
                    "type": "string",
                    "example": "2026-05-03T12:00:00.123Z"
                },
                "severity": {
                    "type": "string",
                    "example": "warning"
                },
                "type": {
                    "type": "string",
                    "example": "high_temperature"
                }
            }
        },
        "auth.AuthData": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "expires_in": {
                    "type": "integer",
                    "example": 900
                },
                "refresh_token": {
                    "type": "string",
                    "example": "ah_refresh_2P8mYwD9kYf3nQxV7bA1cE4rT6uI0oPz"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "auth.AuthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.AuthData"
                },
                "message": {
                    "type": "string",
                    "example": "Login successful"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "client@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "auth.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "ah_refresh_2P8mYwD9kYf3nQxV7bA1cE4rT6uI0oPz"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "client@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "Demo Client"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                }
            }
        },
        "auth.SessionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "9fe9e122-bfb1-4f3b-a2d0-f4acdd4cbd2d"
                },
                "ip_address": {
                    "type": "string",
                    "example": "127.0.0.1"
                },
                "last_used_at": {
                    "type": "string"
                },
                "revoke_reason": {
                    "type": "string",
                    "example": "logout"
                },
                "revoked_at": {
                    "type": "string"
                },
                "token_family": {
                    "type": "string",
                    "example": "0f1f1c17-f9e6-42f3-9341-1555a07ddf4e"
                },
                "user_agent": {
                    "type": "string",
                    "example": "Mozilla/5.0"
                }
            }
        },
        "auth.SessionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/auth.SessionResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Sessions retrieved successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "client.ClientResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "client@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "8c5c8a5e-6b74-48b4-9e0b-85a0c9ef1234"
                },
                "name": {
                    "type": "string",
                    "example": "Acme Inc"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "client.MeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/client.ClientResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Client retrieved successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "common.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Success"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "common.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "details": {}
            }
        },
        "common.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/common.ErrorBody"
                },
                "message": {
                    "type": "string",
                    "example": "Request validation failed"
                },
                "status": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "device.CreateDeviceEnvelopeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/device.DeviceWithAPIKeyResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Device created successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "device.CreateDeviceRequest": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string",
                    "example": "Warehouse Temperature Sensor"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "warehouse",
                        "floor-1"
                    ]
                },
                "type": {
                    "type": "string",
                    "example": "temperature_sensor"
                }
            }
        },
        "device.DeleteDeviceEnvelopeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/device.DeleteDeviceResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Device deleted successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "device.DeleteDeviceResponse": {
            "type": "object",
            "properties": {
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234"
                },
                "purge_after": {
                    "type": "string"
                }
            }
        },
        "device.DeviceEnvelopeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/device.DeviceResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Device retrieved successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "device.DeviceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string",
                    "example": "Warehouse Temperature Sensor"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "warehouse",
                        "floor-1"
                    ]
                },
                "type": {
                    "type": "string",
                    "example": "temperature_sensor"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "device.DeviceWithAPIKeyResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "ah_dev_uTx9s6Cq54wIhj3YgVSLW7B9sPlmY2xL"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234"
                },
                "name": {
                    "type": "string",
                    "example": "Warehouse Temperature Sensor"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "type": {
                    "type": "string",
                    "example": "temperature_sensor"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "device.ListDevicesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/device.DeviceResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Devices retrieved successfully"
                },
                "pagination": {
                    "$ref": "#/definitions/device.PaginationMeta"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "device.PaginationMeta": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean",
                    "example": true
                },
                "has_previous": {
                    "type": "boolean",
                    "example": false
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "device.RotateDeviceAPIKeyEnvelopeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/device.RotateDeviceAPIKeyResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Device API key rotated successfully"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "device.RotateDeviceAPIKeyResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "ah_dev_zr9v7X2kLj8QmP4eNs6CbT1aYw3Fh5Ux"
                },
                "id": {
                    "type": "string",
                    "example": "4d285f4b-2a87-4a86-a5b8-05b09c6d1234"
                },
                "rotated_at": {
                    "type": "string"
                }
            }
        },
        "device.UpdateDeviceRequest": {
            "type": "object",
            "properties": {
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string",
                    "example": "Warehouse Temperature Sensor v2"
                },
                "status": {
                    "type": "string",
                    "example": "maintenance"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "warehouse",
                        "floor-1"
                    ]
                },
                "type": {
                    "type": "string",
                    "example": "temperature_sensor"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Client JWT access token. Use value format: Bearer \u003caccess_token\u003e.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "DeviceAPIKey": {
            "description": "Device API key returned once when creating or rotating a device. Use value format: Bearer ah_dev_...",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "AlertHub API",
	Description:      "AlertHub IoT device management and realtime alert API. Covers device registration (Backlog 1), realtime ingest with SSE (Backlog 2), alert query/filter/pagination (Backlog 3), auto-escalation with Redis cooldown (Backlog 4), and alert search (Backlog 5). Use Authorize -> BearerAuth for client JWT (from /auth/login). Use Authorize -> DeviceAPIKey for device API key (from POST /devices).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
